/**
 * GET /api/review/inventory
 *
 * Returns the video inventory JSON (generated by scripts/review/generate-inventory.ts).
 */
import { NextResponse } from 'next/server'
import { readFileSync, existsSync } from 'fs'
import path from 'path'

export async function GET() {
  const invPath = path.join(process.cwd(), 'data', 'review', 'video-inventory.json')
  if (!existsSync(invPath)) {
    return NextResponse.json({ error: 'Inventory not generated. Run: bunx tsx scripts/review/generate-inventory.ts' }, { status: 404 })
  }
  try {
    const data = JSON.parse(readFileSync(invPath, 'utf8'))
    return NextResponse.json(data)
  } catch (e) {
    return NextResponse.json({ error: 'Failed to parse inventory' }, { status: 500 })
  }
}
